name: Auto pipeline fixer

on:
  workflow_run:
    workflows:
      - Deploy to AWS
      - Per-commit asset audit
    types:
      - completed

jobs:
  attempt-auto-fix:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'failure' &&
          github.event.workflow_run.head_branch == 'main' &&
          github.event.workflow_run.name != 'Auto pipeline fixer' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run auto pipeline fixer
        run: npm run auto:fix
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_FIX_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.AUTO_FIX_OPENAI_API_KEY }}
          TARGET_RUN_ID: ${{ github.event.workflow_run.id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_API_URL: ${{ github.api_url }}
          GIT_AUTHOR_NAME: ${{ secrets.AUTO_FIX_GIT_AUTHOR_NAME || 'InfiniteRails Auto Fixer' }}
          GIT_AUTHOR_EMAIL: ${{ secrets.AUTO_FIX_GIT_AUTHOR_EMAIL || 'auto-fixer@users.noreply.github.com' }}
